/*
 * Copyright (c) 2026, Ibrahim KAIKAA <ibrahimkaikaa@gmail.com>
 * SPDX-License-Identifier: GPL-3.0
 */

#pragma once

#include <stdint.h>

typedef struct
{
    uint32_t width;
    uint32_t height;
} bui_window_resized_event_t;

typedef enum {
    BUI_KEYBOARD_SCANCODE_NULL = 0,
    BUI_KEYBOARD_SCANCODE_ESCAPE = 0x01,
    BUI_KEYBOARD_SCANCODE_1 = 0x02,
    BUI_KEYBOARD_SCANCODE_2 = 0x03,
    BUI_KEYBOARD_SCANCODE_3 = 0x04,
    BUI_KEYBOARD_SCANCODE_4 = 0x05,
    BUI_KEYBOARD_SCANCODE_5 = 0x06,
    BUI_KEYBOARD_SCANCODE_6 = 0x07,
    BUI_KEYBOARD_SCANCODE_7 = 0x08,
    BUI_KEYBOARD_SCANCODE_8 = 0x09,
    BUI_KEYBOARD_SCANCODE_9 = 0x0A,
    BUI_KEYBOARD_SCANCODE_0 = 0x0B,
    BUI_KEYBOARD_SCANCODE_MINUS = 0x0C,
    BUI_KEYBOARD_SCANCODE_EQUALS = 0x0D,
    BUI_KEYBOARD_SCANCODE_BACKSPACE = 0x0E,
    BUI_KEYBOARD_SCANCODE_TAB = 0x0F,
    BUI_KEYBOARD_SCANCODE_Q = 0x10,
    BUI_KEYBOARD_SCANCODE_W = 0x11,
    BUI_KEYBOARD_SCANCODE_E = 0x12,
    BUI_KEYBOARD_SCANCODE_R = 0x13,
    BUI_KEYBOARD_SCANCODE_T = 0x14,
    BUI_KEYBOARD_SCANCODE_Y = 0x15,
    BUI_KEYBOARD_SCANCODE_U = 0x16,
    BUI_KEYBOARD_SCANCODE_I = 0x17,
    BUI_KEYBOARD_SCANCODE_O = 0x18,
    BUI_KEYBOARD_SCANCODE_P = 0x19,
    BUI_KEYBOARD_SCANCODE_LBRACKET = 0x1A,
    BUI_KEYBOARD_SCANCODE_RBRACKET = 0x1B,
    BUI_KEYBOARD_SCANCODE_ENTER = 0x1C,
    BUI_KEYBOARD_SCANCODE_LCTRL = 0x1D,
    BUI_KEYBOARD_SCANCODE_A = 0x1E,
    BUI_KEYBOARD_SCANCODE_S = 0x1F,
    BUI_KEYBOARD_SCANCODE_D = 0x20,
    BUI_KEYBOARD_SCANCODE_F = 0x21,
    BUI_KEYBOARD_SCANCODE_G = 0x22,
    BUI_KEYBOARD_SCANCODE_H = 0x23,
    BUI_KEYBOARD_SCANCODE_J = 0x24,
    BUI_KEYBOARD_SCANCODE_K = 0x25,
    BUI_KEYBOARD_SCANCODE_L = 0x26,
    BUI_KEYBOARD_SCANCODE_SEMICOLON = 0x27,
    BUI_KEYBOARD_SCANCODE_APOSTROPHE = 0x28,
    BUI_KEYBOARD_SCANCODE_BACKTICK = 0x29,
    BUI_KEYBOARD_SCANCODE_LSHIFT = 0x2A,
    BUI_KEYBOARD_SCANCODE_BACKSLASH = 0x2B,
    BUI_KEYBOARD_SCANCODE_Z = 0x2C,
    BUI_KEYBOARD_SCANCODE_X = 0x2D,
    BUI_KEYBOARD_SCANCODE_C = 0x2E,
    BUI_KEYBOARD_SCANCODE_V = 0x2F,
    BUI_KEYBOARD_SCANCODE_B = 0x30,
    BUI_KEYBOARD_SCANCODE_N = 0x31,
    BUI_KEYBOARD_SCANCODE_M = 0x32,
    BUI_KEYBOARD_SCANCODE_COMMA = 0x33,
    BUI_KEYBOARD_SCANCODE_PERIOD = 0x34,
    BUI_KEYBOARD_SCANCODE_SLASH = 0x35,
    BUI_KEYBOARD_SCANCODE_RSHIFT = 0x36,
    BUI_KEYBOARD_SCANCODE_KEYPAD_ASTERISK = 0x37,
    BUI_KEYBOARD_SCANCODE_LALT = 0x38,
    BUI_KEYBOARD_SCANCODE_SPACE = 0x39,
    BUI_KEYBOARD_SCANCODE_CAPSLOCK = 0x3A,
    BUI_KEYBOARD_SCANCODE_F1 = 0x3B,
    BUI_KEYBOARD_SCANCODE_F2 = 0x3C,
    BUI_KEYBOARD_SCANCODE_F3 = 0x3D,
    BUI_KEYBOARD_SCANCODE_F4 = 0x3E,
    BUI_KEYBOARD_SCANCODE_F5 = 0x3F,
    BUI_KEYBOARD_SCANCODE_F6 = 0x40,
    BUI_KEYBOARD_SCANCODE_F7 = 0x41,
    BUI_KEYBOARD_SCANCODE_F8 = 0x42,
    BUI_KEYBOARD_SCANCODE_F9 = 0x43,
    BUI_KEYBOARD_SCANCODE_F10 = 0x44,
    BUI_KEYBOARD_SCANCODE_F11 = 0x57,
    BUI_KEYBOARD_SCANCODE_F12 = 0x58,
    BUI_KEYBOARD_SCANCODE_UP = 0x65,
    BUI_KEYBOARD_SCANCODE_LEFT = 0x67,
    BUI_KEYBOARD_SCANCODE_RIGHT = 0x68,
    BUI_KEYBOARD_SCANCODE_DOWN = 0x6A,
    BUI_KEYBOARD_SCANCODE_DELETE = 0x6D,
} bui_keyboard_scancode_t;

typedef enum {
    BUI_MOUSE_BUTTON_LEFT = 0x01,
    BUI_MOUSE_BUTTON_RIGHT = 0x02,
    BUI_MOUSE_BUTTON_MIDDLE = 0x04,
} bui_mouse_button_t;

typedef struct
{
    uint32_t pos_x, pos_y;
    uint32_t delta_x, delta_y;
} bui_mouse_move_event_t;

typedef struct
{
    bui_mouse_button_t button;
    uint32_t pos_x, pos_y;
} bui_mouse_button_event_t;

typedef struct
{
    uint32_t pos_x, pos_y;
    int32_t delta_x, delta_y;
} bui_mouse_wheel_event_t;

typedef enum {
    BUI_EVENT_NONE = 0,
    BUI_EVENT_WINDOW_CREATED,
    BUI_EVENT_WINDOW_RESIZED,
    BUI_EVENT_WINDOW_CLOSED,
    BUI_EVENT_KEY_DOWN,
    BUI_EVENT_KEY_HOLD,
    BUI_EVENT_KEY_UP,
    BUI_EVENT_MOUSE_MOVE,
    BUI_EVENT_MOUSE_BUTTON_DOWN,
    BUI_EVENT_MOUSE_BUTTON_UP,
    BUI_EVENT_MOUSE_WHEEL,
} bui_event_type_t;

typedef enum {
    BUI_KEY_STATE_UP = 0,
    BUI_KEY_STATE_DOWN = 1,
    BUI_KEY_STATE_HOLD = 2,
} bui_key_state_t;

typedef struct
{
    bui_event_type_t type;
    uint32_t window_id;
    union {
        bui_window_resized_event_t window_resized;
        bui_keyboard_scancode_t keyboard;
        bui_mouse_button_event_t mouse_button;
        bui_mouse_move_event_t mouse_move;
        bui_mouse_wheel_event_t mouse_wheel;
    };
} bui_event_t;
